googlecloudrobotics/core

src/app_charts/base/cloud/apps-crd.yaml, src/bootstrap/cloud/terraform/cluster.tf, src/go/pkg/controller/approllout/controller.go
cr-syncer was not able to sync chartassignments CRD to the robot cluster anymore.
This error occurred on each request:
**E0916 11:56:06.361712       1 reflector.go:126] external/io_k8s_client_go/tools/cache/reflector.go:94: Failed to list *unstructured.Unstructured: the server could not find the requested resource**
Potentially this is related to the fix in this [security bulletin](https://cloud.google.com/kubernetes-engine/docs/security-bulletins#august-05-2019).
Changing the scope of chartassignments CRD from Cluster to Namespaced seems to fix the issue.
Since Kubernetes v1.11 is outdated on GCP, min_master_version is pushed to 1.13
=> Change scope of chartassignments CRD to Namespaced / Increase kubernetes min_master_version to 1.13

src/app_charts/base/cloud/cloud-master.yaml, src/app_charts/base/robot/robot-master.yaml
Fix for issue https://github.com/googlecloudrobotics/core/issues/60
I changed the stable-repo-url to the one Stefan used in his commit 279ebb3.
Cloud-master is using the same `helm init` command and is still starting. Thus, I assume the repo is longer available for GCP services. I made the same change here, because sooner or later it will become invalid from there too.
=> Change stable-repo-url for helm init containers

WORKSPACE, bazel/rbe_config/config/BUILD
16.04 is EOL. This modernizes the hermetic toolchain setup.
Thanks to some changes in how we build the corresponding RBE image, this also reduces its size >10x.
=> Bump LLVM toolchain to Ubuntu 20.04

src/go/cmd/metadata-server/BUILD.bazel, src/go/pkg/gcr/update_gcr_credentials.go
A change to the order in which we update the GCR credentials introduced a bug that prevented us from running pods with images from a private GCR in the default namespace, which is triggered when setting up a new cluster pointed at a CRC dev project.
The BUILD.bazel change was required by the pre-commit hook.
=> Also patch the default/default SA.

src/bootstrap/cloud/terraform/service-account.tf
To reduce the privilege of the token you run setup-robot with, it's safer to give it a token for the human-acl@ SA rather than your own account. However, this currently prevents it from pulling setup-robot from a private GCR, which breaks the dev workflow. Adding this ACL fixes it.
=> Allow running setup-robot with human-acl@ tokens

src/go.mod, src/go/cmd/cr-syncer/BUILD.bazel, src/go/cmd/cr-syncer/syncer.go, src/go/cmd/cr-syncer/syncer_test.go, src/go/cmd/token-vendor/BUILD.bazel
The status's observedGeneration field lets a CR creator identify when a controller has updated the status to reflect a change in the spec. However, because it's tied to the generation field, which is managed by the apiserver, it can't be directly copied between two clusters. Instead, we can preserve the difference between generation and observedGeneration, allowing the CR creator to wait until generation==observedGeneration before looking at the status.
I also needed to bump to Go 1.18 to use `any`.
=> cr-syncer: Preserve observedGeneration semantics

src/go/cmd/cr-syncer/health.go
Previously, it listed all robots on GKE, which can be slow and cause the liveness probe to fail on large projects. Instead, we can just limit it to 1 result - this seems to take 1-2s in my tests with `curl`.
b/277032994
=> Make cr-syncer health check faster

scripts/robot-sim.sh, src/go/cmd/setup-robot/main.go, src/go/cmd/setup-robot/main_test.go
This allows for longer hostnames, in particular those of GCE instances. This doesn't delete the old label, because that's hard with the default "merge labels" behavior of CreateOrUpdateRobot(), so it's easier to manually migrate the labels.
@Ongy
=> Move master-host to an annotation

deploy.sh
This hides a noisy error we'd print on subsequent runs.
=> Add early exit if we already cleaned up the iot-registry.

bazel/repositories.bzl
Pulls in https://github.com/bazelbuild/rules_docker/pull/2233 which is expected by downstream repos. Looks like rules_docker haven't had a labelled release in a while, hence the commit reference.
This corresponds to http://cl/517244821.
=> Bump io_bazel_rules_docker

scripts/include-config.sh
We've used the new setting in many places for a long time. This change is a preparation to drop the option.
=> Flip the CR_SYNCER_RBAC to be `true` by default

bazel/base_images.bzl
Base Go images have been updated to use the latest versions. Images for `gcr.io/distroless/base` and `gcr.io/distroless/static` have been updated.
=> Update Go base images

METADATA, WORKSPACE, current_versions.txt, new_versions.txt, nvchecker.toml, src/app_charts/base/cloud/nginx-ingress-controller-policy.yaml, src/app_charts/base/cloud/nginx-ingress-controller.yaml
This pulls in an Alpine update which should fix some CVE warnings. The newer release is incompatible with k8s 1.23 but GKE has auto-updated to 1.24 everywhere now 1.23 is EOL.
I changed the RBAC policy based on the v1.3.0 release notes (needs permission for coordination.k8s.io/leases). Don't ask me why upstream added it to both the Role and the ClusterRole.
https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.3.0
Tested by deploying to robco-rodrigoq and checking the nginx dashboards in Grafana.
=> Update ingress-nginx to 1.8.0

src/app_charts/base/relay-dashboard.json
The units are actually in seconds. We see long durations, du to use of streaming requests.
=> Update the relay dashboard.

src/go/cmd/http-relay-client/main.go, src/go/cmd/http-relay-client/main_test.go
The relay url is build from commandline flags and cannot change during runtime. Build it just once and reuse.
Besides that it should make the code more readable, it will also help latency and lower GC pressure.
=> Build the relay url just once.

src/app_charts/base/cloud/app-management.yaml, src/go/cmd/app-rollout-controller/main.go, src/go/pkg/controller/approllout/BUILD.bazel, src/go/pkg/controller/approllout/controller.go, src/go/pkg/controller/approllout/controller_test.go, src/go/pkg/controller/chartassignment/validator.go
This change enables inline apps to be versioned as well.
It does so by adopting a label and naming convention,
and using the Version attribute in the Robot selector of
AppRollouts to fetch a different App depending on the version.
It finds those versioned apps using labels, and has a validator to
ensure app names and labels don't drift too far from each other.
Lastly, this change adds unit tests to test the new behavior.
Note: this removes a check in the chartassignment validator, namely that Inline
can now coexist with Version.
TEST=go test ./...
TEST=deploy to intrinsic-coconutruben
=> apps: allow versioned inline apps

.github/ci/common.sh, .github/ci/integration_test.sh
After https://github.com/googlecloudrobotics/core/pull/163 this file was no longer present, which manifests as a broken postsubmit: https://console.cloud.google.com/cloud-build/builds;region=europe-west1/a9a2ed28-0966-49ae-acb4-5e6b11187010;step=1?project=robco-integration-test
Also fixing a missing rename in https://github.com/googlecloudrobotics/core/pull/159
Postsubmit passes with this PR: https://pantheon.corp.google.com/cloud-build/builds;region=europe-west1/6e67162e-b19d-435a-8726-15c3bf202255?project=robco-integration-test
=> Fix path to image push script

.github/ci/common.sh, .github/ci/integration_test.sh, deploy.sh
I missed this in https://github.com/googlecloudrobotics/core/pull/186.
Now tested by actually running this part of the code too: https://github.com/googlecloudrobotics/core/actions/runs/5655155089
https://github.com/googlecloudrobotics/core/actions/runs/5655020052
How we read the setup robot digest also needed to change, as the `.json` was not part of the binary distribution. I manually checked that `bazel-bin/src/bootstrap/cloud/setup-robot.digest` and `src/go/cmd/setup-robot/setup-robot-image/index.json` contains the same digest.
=> More fixes post OCI migration

src/go/tests/relay_test.sh
This should be less dependent on the configuration of the target
container. With this I was able to get some passing tests on my personal
project, although the behavior doesn't seem 100% reproducible (even when
waiting for the pods to update after ./deploy.sh).
b/293827843
=> Use `echo` instead of `id` to test kubectl exec

src/app_charts/base/relay-dashboard.json
The previous window of 10 minutes lead to a significant low-pass filtering, smearing the data.
=> Use auto aggregation interval

.github/ci/common.sh
This aligns the scp invocation with the ssh in this file and makes it slightly simpler to run integration_test.sh locally (still hard, see b/294963266).
=> Hard code builder user

src/app_charts/base/cloud/nginx-ingress-controller.yaml
Why?
This allows the nginx-ingress-controller to scale horizontally when under load. Load is directly correlated to cpu usage in the case of the nginx-ingress-controller
=> Add HPA to the nginx-ingress-controller

deploy.sh, src/bootstrap/cloud/terraform/cluster.tf, src/bootstrap/cloud/terraform/service-account.tf, src/bootstrap/cloud/terraform/workload-identity.tf
This will be useful for pods that we can't easily scale horizontally and
are tolerant of downtime. Also, reformat the Terraform files to make the
pre-commit hook happy.
=> Enable vertical autoscaling on GKE.

src/go/cmd/token-vendor/main.go
We have seen that on the integration test project the current default limit of 5 is reached.
=> Add option to configure Kubernetes QPS limit.

src/go/cmd/token-vendor/main.go
This reverts commit 38fec517958adcd03371e5a8ffc6a5a4769ca6fa. It causes
token-vendor to panic with `"burst is required to be greater than 0 when
RateLimiter is not set and QPS is set to greater than 0"`.
=> Revert "Add option to configure Kubernetes QPS limit. (#206)"

src/go/cmd/token-vendor/main.go
We have seen that on the integration test project the current default limit of 5 is reached.
This second iteration of the PR fixes the missing burst parameter.
=> Add option to configure Kubernetes QPS limit (fixed burst parameter)

src/go/cmd/http-relay-server/server/BUILD.bazel, src/go/cmd/http-relay-server/server/server_test.go
After adding tracing, it was a wrong assumption to assume that the X-Deadline was stored as the first entry in a header. Manually removing the traceparent turns out to be the correct and reliable solution.
=> Fixes issue #207

src/bootstrap/cloud/terraform/service-account.tf
Projects that are build on-top of this infrastructure will need to add the permission as needed.
=> Remove unused permission from robot-service.

src/go/cmd/http-relay-server/server/server.go, src/go/cmd/http-relay-server/server/server_test.go, src/go/tests/relay/BUILD.bazel, src/go/tests/relay/nok8s_relay_test.go
The relay client splits responses from the backend into multiple chunks based on MaxChunkSize and sends these chunks to the relay server. Currently, the relay client includes HTTP trailers in the last chunk sent - which makes sense - but the relay server code does not correctly handle the case with more than one chunk and always returns the trailers sent with the first chunk (ignoring the trailers in all other chunks). Thus when chunking responses we currently do not return any trailers. 
This PR fixes this issue in the relay server by handling trailers similar to the message body and collecting all trailers from all chunks before appending them to the HTTP response sent to the user client. We add an integration test and unit tests that cover chunked responses.
This fixes the issue that …
=> Fix handling of trailers in relay when chunking

src/app_charts/base/relay-dashboard.json
The total number of backends that have ever connected doesn't appear to be a good metric.
Getting a good guess at which clients are currently online is a more useful measure.
=> Update http relay dashboard

src/go/cmd/http-relay-client/client/client.go, src/go/cmd/http-relay-server/server/broker.go, src/go/cmd/http-relay-server/server/server.go, src/go/tests/relay/nok8s_relay_test.go
Same as #220, but ported to this repo.
---
When the user client closes the connection, it is not propagated to the backend. For simple "one shot" requests, there is no huge impact as the response would just be dropped, however for long running requests (chunked encoding or websockets), the backend doesn't know that the user client has closed the connection and it keeps sending new updates to the relay client, which also doesn't know and so keep forwarding that to the relay server.
The fix applied is:
* Add `StopRelayRequest` to the broker to "forget" a relaying request. This will cause the relay server to response with a permanent error the next time the relay client tries to send a response for that id. This will in turn cause the relay client to close the connection to the backend.
* …
=> fix leaking connections when user client closes connection

src/app_charts/base/robot/cr-syncer.yaml
On our integration test project, this makes up 90% of the requests from
the cr-syncer. I hope this will reduce the load on nginx.
b/299409898
=> Increase cr-syncer health check period

src/go/cmd/http-relay-client/client/client.go, src/go/cmd/http-relay-client/client/client_test.go, src/go/cmd/http-relay-server/server/broker_test.go, src/go/cmd/http-relay-server/server/server.go, src/go/cmd/http-relay-server/server/server_test.go
This doesn't change the formatting but is more consistent with our other
error format strings.
I also fixed the location of a string due to an unclear review comment I
made.
=> Use %v instead of %s in relay logs

src/bootstrap/cloud/terraform/service-account.tf, src/go/cmd/http-relay-client/client/client.go, src/go/cmd/http-relay-client/client/client_test.go, src/go/cmd/http-relay-server/server/broker.go, src/go/cmd/http-relay-server/server/broker_test.go, src/go/cmd/http-relay-server/server/server.go, src/go/cmd/http-relay-server/server/server_test.go, src/go/tests/relay/nok8s_relay_test.go
It causes the postsubmit integration test to fail with:
```
error: Timeout occurred
TEST FAILED: echo command did not run, output was "", want "hello"
```
when testing `kubectl exec`.
https://source.cloud.google.com/results/invocations/8f0b86f7-c5c4-41a3-9e4c-43e325d9e1ae/targets/%2F%2Fsrc%2Fgo%2Ftests:relay_test/log
- Revert "Use %v instead of %s in relay logs (#224)"
- Revert "fix leaking connections when user client closes connection (#222)"
=> Revert #222

src/bootstrap/cloud/terraform/service-account.tf, src/go/cmd/http-relay-client/client/client.go, src/go/cmd/http-relay-client/client/client_test.go, src/go/cmd/http-relay-server/server/broker.go, src/go/cmd/http-relay-server/server/broker_test.go, src/go/cmd/http-relay-server/server/server.go, src/go/cmd/http-relay-server/server/server_test.go, src/go/tests/relay/BUILD.bazel, src/go/tests/relay/nok8s_relay_test.go
Fix end-to-end failure from #222.
The problem is mistakenly using `w.Write` at server.go:260, the response writer is no longer valid after the connection has been hijacked, we need to use `bufrw.Write` instead.
=> fix leaking connections 2nd try

src/go/cmd/http-relay-server/server/server.go
Tested by using curl through a relay-server to a slow backend, and seeing the relay-server responding with a "HTTP/2 504" error instead of 500 and "Timeout after 1m0s, indicating that the backend request took too long" in the body.
Copied from here https://github.com/googlecloudrobotics/core/pull/227 to make the presubmit tests to work.
=> Changed the http status code from 500 Internal Server Error to 504 Gateway Timeout after timing out from the backend

src/go/cmd/http-relay-server/server/broker.go, src/go/cmd/http-relay-server/server/broker_test.go
Previously it only removed exactly 20 characters of hex characters,
rather than 20+ characters, which severely limited its value. I promise
that this is my last attempt to save this duct-tape solution, and next
time I will remove request_path from the URL entirely.
=> Fix a silly error in URL cleanup

src/bootstrap/cloud/terraform/service-account.tf
This is a step towards removing the blanket objectAdmin ACL. (b/299475780)
As far as I can tell, robot-service@ does not need to read other files
from CRC buckets (config.sh, crc_version.txt, etc) in the general case,
although integration tests might need more privilege.
=> Allow robot-service@ to read from GCR explicitly.

src/bootstrap/cloud/terraform/service-account.tf
This reverts commit 4f2065c322c12b77372f526c1f32c789ff9ec2fe. It breaks
on projects with "eu.artifacts..." buckets like the "navtest" CI
project.
=> Revert "Allow robot-service@ to read from GCR explicitly. (#234)"

src/go/cmd/metadata-server/metadata.go, src/go/cmd/metadata-server/metadata_test.go
If the token-vendor encounters an error (such as being rate-limited by
the k8s apiserver), the metadata-server will retry as fast as it gets
requests from on-prem clients, which can be quite fast, as they don't
expect a round-trip to the cloud but just a local request.
This change applies exponential backoff with a max delay of around 2
minutes. I tested by turning off the token-vendor in robco-rodrigoq,
waiting for the metadata-server's token to expire, waiting another hour
or so, then turning it back on, and observing that it got a token within
a few minutes.
Alternative considered: Instead of using the TokenSource interface, I
could have created a goroutine that periodically refreshes the token and
does normal retries on failure, but this approach feels more composable?
(although the …
=> Rate-limit token requests on error

src/bootstrap/cloud/terraform/cluster.tf
* monitoring.viewer is already covered by monitoring.metricWriter
* stackdriver.resourceMetadata.writer is unused
Tested on robco-ensonic gcp project.
=> Reduce permissions on gke-node service account.

.github/ci/integration_test.sh, .github/ci/presubmit.sh, src/go/tests/BUILD.bazel, src/go/tests/apps/BUILD.bazel
The Bazel team hosts a CI project on Buildkite, which expects to be able
to run all our tests with recent versions of Bazel. We like this because
the Bazel team file issues on our repo to tell us when a future Bazel
release will break our build, but to keep this, we need to make sure our
project is always green on their CI. I don't know why, but we just got a
report that our integration tests are red there due to missing
dependencies (kubectl, docker, credentials): #4380.
We can work around this by using the "manual" tag to exclude our tests
from target expansion, and then manually listing them in our own CI.
I will need to manually check that the tests are still running in
presubmit and postsubmit.
=> Hide integration tests from Buildkite CI

WORKSPACE
Deployed to personal project for testing.
See b/269420958.
=> Bump distroless images.

METADATA, current_versions.txt, src/app_charts/base/cloud/nginx-ingress-controller.yaml
Not updating to 1.9.X yet, as there are breaking changes (*-snippet annotations are disabled and we use them for error pages).
https://github.com/kubernetes/ingress-nginx/releases
=> Update the nginx-inress to 1.8.4.

config.sh.tmpl, deploy.sh
We can add PRIVATE_DOCKER_PROJECTS anywhere it is necessary. The
transition helper breaks when switching between source and binary
deployments on the same project, because it's not valid to compare
CLOUD_ROBOTICS_CONTAINER_REGISTRY (which has the gcr.io/ prefix) and
GCP_PROJECT_ID (which doesn't).
Tested by inserting `exit 1` into deploy.sh before it doesn't anything
dangerous, then running `bash -x deploy.sh update my-binary-project`.
=> Remove four-year-old transition helper.

src/go/cmd/token-vendor/oauth/BUILD.bazel, src/go/cmd/token-vendor/oauth/verifier.go
This change adds retries with static retry interval to the TestIamPermissions calls. Exponential retries should not be necessary here with the small number of retries.
=> Add retry for TestIamPermissions on context deadline exceeded.

config.sh.tmpl, deploy.sh, scripts/include-config.sh, src/bootstrap/cloud/terraform/input.tf, src/bootstrap/cloud/terraform/service-account.tf
This has been in use for a while. However, CR_SYNCER_RBAC is not
consistently true across all our projects - leading to excessive
robot-service@ privileges in some case. Deleting this simplifies the
code and improves security.
After this is applied, robot-service@ will be limited to "Kubernetes
Engine Cluster Viewer" in all other projects, which allows it to list
GKE clusters (via IAM) and other Robot CRs and ChartAssignments (via
RBAC) but not much more. This role is not to be confused with
"Kubernetes Engine Viewer" which would allow reading all resources in
the GKE clusters, rather than just listing clusters and reading select
resources.
=> Delete obsolete CR_SYNCER_RBAC flag

src/app_charts/base/cloud/app-management.yaml
readOnlyRootFilesystem is a container setting, not a pod setting. Fixes a warning when installing the chart.
=> Drop duplicated setting from the wrong place.

src/app_charts/base/cloud/cert-manager-certificates.yaml
This fixes a warnign on the cert validation. I wend back in the git history and can't figre why we have these lines here. These belong to the issuer config and are not valid fro Certificates, see
https://cert-manager.io/docs/usage/certificate/
=> Remove invalid part of certificate spec.

src/go.mod, src/go.sum, third_party/go_repositories.bzl
the dependency is already removed in all packages. this removes the last references.
=> removed logrus dependency

src/bootstrap/cloud/terraform/cluster.tf
Allow to scale down to 1 if there is not a lot of load (might especially help on -ar clusters and dev setups). Bump max size on base-pool to 16 as we have hit that limit in some setups.
=> Adjust node-pool limit.

src/app_charts/base/cloud/app-management.yaml, src/app_charts/base/robot/app-management.yaml
(removed the protocol:tcp from yaml as that's the default).
Tested on robco-ensonic
See b/315345823
=> Use the health-probes from the controller-runtime as liveness probes.

scripts/backup_robots.sh
This is mostly FYI. I don't like the hacks it requires. If I run this against g-w I get a 0.5 mb yaml and there are a lot of pubkeys:
```
egrep "^kind:" /tmp/crc-backup.yaml | sort | uniq -c
706 kind: ConfigMap
78 kind: Robot
```
Some of them are stale, but token-vendor can't do the cleanup, because the robot-cr is not necessarily available in the cloud.
Also the filtering is sub-par. WDYT if I change token-vendor to label them (and backfill the label via script).
=> Extend the backup script to also backup the pubkeys.

scripts/backup_robots.sh, src/go/cmd/token-vendor/repository/k8s/k8s.go
This will let us efficiently filter, e.g. when backing them up. Adjust the backup script to filter by label.
Existing registrytion can be backfilled by e.g.:
```bash
function kc {
kubectl --context="${KUBE_CONTEXT}" -n app-token-vendor "$@"
}
for cm in $(kc get cm -o name | egrep "^configmap/robot-"); do
kc label "$cm" --overwrite app.kubernetes.io/managed-by=token-vendor
done
```
See also: #320
=> Add a label to the pubkey configmap.

.github/ci/deploy_navtest.sh, .github/ci/deploy_navtest_cloudbuild.yaml, .github/workflows/release.yml
Because of Terraform being too old (b/323509860), I'm blocked on landing https://github.com/googlecloudrobotics/core/pull/323 since `deploy_navtest.sh` does not work with WIF.
This circumvents the problem by running it on Cloud Build (using "within cloud credentials") instead of directly on the action runner.
I had to remove curl `--fail-with-body` because the version of curl in the cloud build image is too old and it is non-trivial to upgrade it on Ubuntu 20. And building a custom image just for this seemed overkill. In https://github.com/googlecloudrobotics/core/pull/239, the motivation was not this particular call site but the GitHub API calls, which are still kept as is.
=> Deploy navtest on cloud build

src/app_charts/base/cloud/oauth2-proxy.yaml
We're calling https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/testIamPermissions and for that we only need 'auth/iam'.
=> Reduce the required scope on the oauth2-proxy.

src/app_charts/base/cloud/oauth2-proxy.yaml
This makes it optional for installtions that don't use it. Right now we would produce a crash-looping instance in that case.
=> Only deploy oauth2-proxy if client-id and -secret are configured.

src/go/pkg/controller/chartassignment/BUILD.bazel, src/go/pkg/controller/chartassignment/release.go
see b/207673353
there was a difference between manifest parsing in synk and in the chart-assignment-controller. the handling of 'kind: List' was causing an infinite resource creation by the controller but was handled correctly by synk. with this change manifest parsing is done by cli-runtime/pkg/resource as is already the case for synk.
=> chart-assignment-controller: use the same resource builder as synk

.github/ci/integration_test.sh, src/go/tests/BUILD.bazel
... which is broken: https://github.com/googlecloudrobotics/core/issues/346
This will only work until robot-sim needs to be re-installed, so it is a ticking time bomb.
Also fixed Bazel invocations, this still runs (only) the two tests previously explicitly mentioned.
=> Fix postsubmit by skipping install_k8s_on_robot.sh

src/go/cmd/cr-syncer/syncer.go
reduce the log level of
'Got Event' and 'Copied status to upstream' from Info to Debug. They are responsible for nearly all log entries.
=> cr-syncer: reduce log level of the 2 most noisy messages

src/go/cmd/http-relay-client/client/client.go, src/go/cmd/http-relay-client/main.go
the cl also adds a command line flag to modify the log level at which messages get logged.
this should significantly reduce the number of log messages produced.
=> frontend-relay-client: reduce the log level of the top 2 messages

bazel/repositories.bzl
This fixes #358. With this, it should now be able to follow the docs at https://github.com/bazelbuild/rules_go/wiki/Editor-setup and have gopls working.
=> update rules_go to v0.46.0

src/go/cmd/http-relay-server/server/server.go
This simply logs when a health check fails to make it easier to debug when kubernetes tries to restart it.
=> Add log when health check fails

src/app_charts/prometheus/prometheus-robot.values.yaml
Larger segment size make it to that WAL truncation does not happen regularly. The current sizes correlate with the retention size.
=> Reduce prometheus robot segment sizes

src/app_charts/prometheus/values-cloud.yaml
Adds smtp related variables to values-cloud.yaml.
```
gf_smtp_host
gf_smtp_user
gf_smtp_password
gf_smtp_from_address
gf_smtp_from_name
gf_smtp_skip_verify
```
Follow up to https://github.com/googlecloudrobotics/core/pull/369
=> Add remaining smtp related variables to values-cloud.yaml

.github/ci/integration_test_cloudbuild.yaml
Some green runs were close to 20m (I saw one at 18m) so this should make it more robust to unexpectedly slow dependencies like BES.
=> Allow 30m for integration_test.sh

.github/workflows/postsubmit.yml
This means that when a release fails, you can push a fix to main and rerun to create the daily release.
=> Allow bypassing manual-run protection

.github/ci/integration_test.sh, .github/workflows/postsubmit.yml
This avoids needing to manually delete lock files after timeouts.
=> Use GitHub's concurrency control

docs/overview.md
I just fixed a typo in  `docs/overwiew.md`. 
It's not much, but I believe anything help.
Keep up the good work team :rocket:  ! (Really interesting project)
=> Fix typo in overview.md

.github/workflows/release.yml
Without this parameter, the API will also return commits from PRs, which
may not have been reviewed and could be malicious.
This has the downside that if you're trying to fix the release workflow
you need to change the schedules or be limited to one attempted fix per
day, but the alternatives (see below) are also not ideal.
For defense in depth, we also check against the head_repository id, which I tested by temporarily changing `event=schedule` to `actor=totoro642`, [in which case the action fails](https://github.com/googlecloudrobotics/core/actions/runs/9662992790/job/26654091527) with:
```
Unexpected head repository ID: 817231418 - check postsubmit.yml configuration
```
Alternatives considered:
- Changing postsubmit to run on `push` and then having the release workflow filter with …
=> Only consider scheduled postsubmit runs

deploy.sh
We don't need the GCR permissions anymore.
=> Drop legacy GCR permission setup from deploy.sh

.github/ci/deployments/robco-integration-test/config.sh, .github/ci/deployments/robco-navtest/config.sh, .github/ci/integration_test.sh, scripts/robot-sim.sh
I've also updated the config.sh files in the bucket. Not sure we we also have them in git.
=> Drop custom vars for cloud-robotics k8s cluster context

.github/ci/integration_test.sh, deploy.sh, scripts/common.sh, scripts/robot-sim.sh
This new helper works for both zonal and regional clusters. It also takes care of preservice the default context. The later should make the calling code easier to read.
See b/323148080
=> Extracted helper for getting cluster credentials.

src/go/pkg/controller/chartassignment/release.go, src/go/pkg/synk/synk.go
Previously, we had a hacky heuristic on when to trust partial discovery
information from the server, but this would still fail to apply
ChartAssignments when it got the error "stale GroupVersion discovery".
Instead, we can treat such errors as warnings, and instead look for
whether the resources in the charts are represented in the discovery
information.
Also, to reduce the frequency of the warnings, invalidate the discovery
cache before calling discovery - this means you just see the warning
once (due to a race in the apiserver I think) instead of the entire time
until the process is restarted.
Fixes #261. (well, we don't actually crash as that issue requests, but I like this way more)
=> Avoid hanging after custom metrics are removed

docs/concepts/app-management.md, src/go/pkg/controller/chartassignment/controller.go
The label cloudrobotics.com/opt-out-error-checking=true when set on a pod will opt it out of the chartassignment controller's error checking routine.
=> Add a way to opt out of status checking

src/app_charts/token-vendor/cloud/ingress.yaml, src/go/cmd/token-vendor/README.md, src/go/cmd/token-vendor/api/v1/v1.go, src/go/cmd/token-vendor/api/v1/v1_test.go, src/go/cmd/token-vendor/app/tokenvendor.go
This allows users to configure proxies (e.g. nginx) to defer authentication to the token vendor not just via the OIDC token, but already with the JWT. Providing this method allows to authenticate "from the first request" without having to first allow traffict to the token vendor from the client. Which is useful to allow an authenticated proxy that's on the route between the client and the token-vendor.
TESTED=auto, not yet in practice
=> Allow forward authentication with robot JWT

deploy.sh, scripts/common.sh, scripts/config.sh, scripts/include-config.sh, scripts/set-config.sh, src/bootstrap/cloud/terraform/cluster.tf, src/bootstrap/cloud/terraform/input.tf
So far we always created "zonal" clusters. This set of changes introduced a new config.sh var `GKE_CLUSTER_TYPE` that defaults to "zonal". This var will be feed into terraforms input vars and allows to select create "regional" clusters instead.
=> Allow to configure CRC to use regional clusters

WORKSPACE, bazel/app.bzl, bazel/app_chart.bzl, bazel/build_rules/app_chart/cache_gcr_credentials.bzl, bazel/build_rules/app_chart/push_all.bzl, bazel/build_rules/app_chart/run_parallel.bzl
Address the error from the migration tool:
```
Please remove the usages of referring your own repo via `@cloud_robotics//`, targets should be referenced directly with `//`.
```
=> Remove @cloud_robotics prefix.

config.sh.tmpl, deploy.sh, src/bootstrap/cloud/terraform/input.tf
This is a no-op still, but will let us enable/disable layer 1 (robot-service account, robot bucket and tokenvendor). This is useful to test and/or use only subsets of the stack.
=> Introduce a new customization var for layer 1.

.github/ci/common.sh
This test is broken:
https://github.com/googlecloudrobotics/core/actions/runs/10915333292/job/30294911657
The code in common.sh is the same as for deploy.sh and there it works :/
=> Add debug code to common.sh

deploy.sh
When running locally I get:
```
MANUAL_RUN=1 ./deploy.sh update robco-ensonic
...
runfiles: --------------------
-r-xr-xr-x 2 ensonic primarygroup 406 Sep 17 07:20 ./external/_main~extension_for_rules_oci~distroless_cc_linux_amd64/layout/index.json
-r-xr-xr-x 1 ensonic primarygroup 292 Sep 17 07:37 ./src/go/cmd/setup-robot/base_image_with_files/index.json
-r-xr-xr-x 1 ensonic primarygroup 292 Sep 17 07:37 ./src/go/cmd/setup-robot/setup-robot-image/index.json
runfiles: --------------------
```
=> Add more ci debug logging.

.github/ci/.bazelrc
Things seem to break with --remote-download-minimal
=> Revert to `--remote-download-toplevel`

BUILD.bazel, MODULE.bazel.lock, bazel/build_rules/helm_chart.bzl, extension_for_rules_oci.bzl, non_module_deps.bzl, src/go/cmd/chart-assignment-controller/BUILD.bazel, src/go/cmd/cr-syncer/BUILD.bazel, src/go/cmd/gcr-credential-refresher/BUILD.bazel, src/go/cmd/setup-robot/BUILD.bazel, src/go/cmd/token-vendor/BUILD.bazel, src/go/pkg/configutil/BUILD.bazel, src/go/pkg/gcr/BUILD.bazel, src/go/pkg/robotauth/BUILD.bazel, src/proto/http-relay/BUILD.bazel, third_party/kubernetes_proto/meta/BUILD.bazel, third_party/kubernetes_proto/runtime/BUILD.bazel, third_party/kubernetes_proto/schema/BUILD.bazel
Ran:
```
buildifier --lint=fix $(find . -name "BUILD.bazel" -o -name "*.bzl")
```
We do have a presubmit-hook (https://github.com/googlecloudrobotics/core/blob/main/scripts/pre-commit#L66-L72), but that does not do the lint part (https://github.com/bazelbuild/buildtools/blob/main/buildifier/README.md#linter)
=> Cleanup bazel files.

third_party/kubernetes_proto/meta/BUILD.bazel, third_party/kubernetes_proto/runtime/BUILD.bazel, third_party/kubernetes_proto/schema/BUILD.bazel
Ran:
```
buildifier --lint=fix --warnings=native-proto $(find . -name "BUILD.bazel" -o -name "*.bzl")
```
Fixes: #24
=> Import proto rules.

src/bootstrap/cloud/BUILD.bazel
I am not sure if anything relies on the file name and path, so I kept the `genrule` but use a `cp`.
=> Use digest target from rules_oci directly

src/app_charts/base/app_management_test.sh
This has been recommened in:
https://bazel.build/concepts/dependencies#data-dependencies
and hopefully fixes the tests on buildkite, see
https://github.com/googlecloudrobotics/core/issues/417#issuecomment-2360650787
=> Use ${TEST_SRCDIR}/_main/ to reference test-data.

deploy.sh, src/bootstrap/cloud/terraform/gcs.tf, src/bootstrap/cloud/terraform/registry.tf, src/bootstrap/cloud/terraform/service-account.tf
* make the -robot bucket optional
* make the robot-service account optional
I wanted to also avoid the token-vendor rollout in base-cloud, but that is related to human-acl and oauth2-proxy usage.
=> Start to apply the layer 1 customization.

src/bootstrap/cloud/terraform/service-account.tf
We've switched to GAR and that setup is covered by registry.tf.
Tested using: `./scripts/robot-sim.sh create robco-ensonic sim1`
robco-ensonic uses PRIVATE_DOCKER_PROJECTS=robco-team
=> Drop storageviewer for the foreign GCR registry buckets,

MODULE.bazel
We can now specify platform directly, so we use the manifest and platform now directly and the outdated comment for debian-iptables has been removed.
The `iptables_base` image doesn't have a latest tag: https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/debian-iptables
=> Restore comments which have been lost in the Bzlmod migration

.bazelrc, deploy.sh, src/app_charts/base/app_management_test.sh, src/go/pkg/kubetest/kubetest.go
This avoids the complexity of handling two different paths.
See #447.
=> Enable --incompatible_use_plus_in_repo_names

bazel/app_chart.bzl, bazel/build_rules/helm_chart.bzl
This prepares us for bazel-head. We still need to bump used rules (e.g. rules_oci) when they ship a fix.
See #451.
=> Add toolchain=None to shell actions.

src/app_charts/prometheus/prometheus-robot.values.yaml
We added container_network.* to the wrong part of the values so they are
still the highest-cardinality metrics (around 15% of all metrics).
Most of the new lines are copy-pasted from the default values.yaml in the Chart, this change just adds container_network.
Tested by using `bazel build
src/app_charts/prometheus/prometheus-operator-chart.robot.yaml` to build
the YAML and diffing:
```
--- /tmp/before.yaml    2024-10-10 15:40:11.686509000 +0000
+++ /tmp/after.yaml     2024-10-10 15:52:02.595166797 +0000
@@ -1192,7 +1192,7 @@
sourceLabels:
- __name__
- action: drop
-      regex: container_spec.*
+      regex: container_spec.*|container_network.*
sourceLabels:
- __name__
- action: drop
```
then manually applying this change with k9s to a lab system and
verifying that the metric stops …
=> Actually drop container_network metrics

src/app_charts/prometheus/prometheus-robot.values.yaml
After these, we're down to useful metrics like node_cpu_seconds_total or
grpc_io_client_roundtrip_latency_bucket which we wouldn't want to drop
but perhaps relabel (for example to aggregate CPU usage across all CPUs
rather than generating 8 metrics for all 30 or 100 vCPUs on every node,
or to drop pod IDs from grpc client metrics so they're aggregated across
different instances of the same client) but I've never tried this.
Tested as for #453.
=> Drop more heavy metrics

src/app_charts/prometheus/robot/smartctl-exporter.yaml
This exports metrics for both SATA and NVMe drives (even if it
annoyingly generates a completely different set of metrics in the two
cases). The container is relatively light at 30MB (!).
This will let us see historic drive temperatures and error rates if we
start to notice drive-related problems in future.
I considered putting this behind a Helm value, but I expect we want
these metrics everywhere, and if they break something we can just roll
back the CRC change.
Tested with kubectl apply on the YAML file.
=> Add smartctl-exporter

src/go/cmd/token-vendor/BUILD.bazel, src/go/cmd/token-vendor/api/v1/v1.go, src/go/cmd/token-vendor/app/BUILD.bazel, src/go/cmd/token-vendor/app/tokenvendor.go, src/go/cmd/token-vendor/main.go, src/go/cmd/token-vendor/repository/BUILD.bazel, src/go/cmd/token-vendor/repository/k8s/BUILD.bazel, src/go/cmd/token-vendor/repository/k8s/k8s.go, src/go/cmd/token-vendor/repository/k8s/k8s_test.go, src/go/cmd/token-vendor/repository/memory/BUILD.bazel, src/go/cmd/token-vendor/repository/memory/memory.go, src/go/cmd/token-vendor/repository/memory/memory_test.go, src/go/cmd/token-vendor/repository/repository.go, src/go/cmd/token-vendor/tokensource/gcp.go
One can already configure a custom service account by using the annotation on the configmap. The api will be added in teh next changes.
=> Allow using a custom service account on an ipc-registration.

src/go/cmd/token-vendor/api/v1/v1_test.go, src/go/cmd/token-vendor/app/tokenvendor.go, src/go/cmd/token-vendor/main.go, src/go/cmd/token-vendor/tokensource/gcp.go
Now it always gets the service-account-name. Putting the amail together has been move up to main.
This way we can log the used service accoutn in one place.
=> Make tokensource less stateful.

src/bootstrap/cloud/run-install.sh
When restoring a backup, it is useful to run the individual install steps.
See b/323148080
=> Extend run-install to allow only applying terraform config.

src/app_charts/base/cloud/kubernetes-api.yaml
The ingress is used by the cr-syncer.
See #440
=> We only need to expose the GKE k8s api if we enable onprem-federation.

src/app_charts/base/cloud/kubernetes-api.yaml
There is no auth-proxy configurred on this ingress.
=> Remove outdated comment and snippet.

src/go/cmd/http-relay-client/client/client.go
=> add exponential backoff when connection to server fails

MODULE.bazel.lock, deploy.sh, non_module_deps.bzl, src/bootstrap/cloud/terraform/versions.tf
This inbetween version is required as it introduces the provider config (see verisons.tf).
=> Upgrade terraform to v0.13.7.

deploy.sh, src/bootstrap/cloud/terraform/gcs.tf
1) We reference the config bucket from a lot of the scripts and docs. Hence
make sure we also create it here. Use terraform import cli, since we're
still on a too old version for using the import statement.
2) create the crc version in the config bucket, as the setup-robot is
conditional.
=> Import the config bucket and put installed version file there.

config.sh.tmpl, deploy.sh, src/bootstrap/cloud/terraform/cluster.tf, src/bootstrap/cloud/terraform/input.tf
This allows integration with the secret manager via kubernetes secrets. It allows to keep secrets secure while providing it to applications via file.
Current intended usecase is an auth_password_file for alertmanager.
TESTED=not yet
=> Add support for enabling secret manager plugin on cluster

src/app_charts/k8s-relay/cloud/kubernetes-relay-server.yaml, src/app_charts/prometheus/cloud/prometheus-relay.yaml
This aligns with the client names and makes it easier to find them in the logs.
=> Use longer names for the relay servers.

src/go/cmd/token-vendor/README.md, src/go/cmd/token-vendor/app/tokenvendor.go, src/go/cmd/token-vendor/repository/k8s/k8s.go, src/go/cmd/token-vendor/repository/memory/memory.go, src/go/cmd/token-vendor/repository/repository.go, src/go/cmd/token-vendor/tokensource/gcp.go
This allows for setups where actual permisisons are granted on the delegate and the robot-sa only needs the permisisons to impersonate the delegate.
See b/367635510
=> Add support for intermediate delegates.

docs/concepts/device_identity.md, src/go/cmd/token-vendor/app/tokenvendor.go
For the 2nd, update the link to the new codebase.
=> Fix references of the old java token vendor.

src/go/pkg/robotauth/robotauth.go
Leave the scopes empty
This is optional and we already sent the data else where. I've deployed this to robco-ensonic and connected minikube to it. I also started hello-k8s and observed that the logs are captured in the cloud.
Add some more comments on the other fields as well.
=> Cleanup robotauth tokensource config.

.github/workflows/presubmit.yml
I hope this will fix the presubmit which currently fails with:
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 6998d139ddd3e68c71e9e398d8e40b71a2f39812`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> Update to actions/cache v4.2.0

src/app_charts/akri/BUILD.bazel, src/app_charts/k8s-relay/BUILD.bazel, src/app_charts/prometheus/BUILD.bazel, src/app_charts/token-vendor/BUILD.bazel, src/go/cmd/token-vendor/repository/k8s/BUILD.bazel, src/go/cmd/token-vendor/repository/memory/BUILD.bazel, src/go/pkg/controller/chartassignment/BUILD.bazel, src/go/pkg/robotauth/BUILD.bazel, src/go/pkg/setup/BUILD.bazel, src/proto/http-relay/BUILD.bazel
This looks to be a no-op but makes it easier to keep BUILD dependencies
up to date with `bazel run :gazelle`.
=> Run Gazelle to fix BUILD files

src/go/cmd/http-relay-server/server/broker.go, src/go/cmd/http-relay-server/server/broker_test.go
`pr.requestStream` may be closed while it is writing because there is no mutex protecting it. This can happen when the request is reaped due to inactivity, if this happens then the server will panic.
=> Protect PutRequestStream with a mutex

src/app_charts/base/fluent-bit-values.yaml, src/app_charts/base/robot/fluent-bit.yaml
When aggregating logs from many peers, we'll see a lot of variance in this field. All teh infomation is already conatin in teh record, so replace the field with a more static valud. This is a similar approach that GKE takes.
Note: the stackdriver plugin adds the projects/<project-id>/logs prefix.
See https://github.com/fluent/fluent-bit/issues/9897
=> Replace logName field to avoid a high cardinality field on stackdriver

src/bootstrap/cloud/terraform/cluster.tf
For deployments that choose to be reginal, the same reason applies to all their clusters.
=> Also apply cluster_type settings to AR clusters.

scripts/robot-sim.sh, src/app_charts/base/robot/gcr-credential-refresher.yaml, src/app_charts/base/robot/metadata-server.yaml, src/app_charts/base/values-robot.yaml, src/go/cmd/metadata-server/main.go, src/go/cmd/setup-robot/main.go
This makes the GKE environment more similar to real systems, and in
particular will let the cr-syncer fetch robot JWTs from the
metadata-server.
Tested with:
```
./deploy.sh update my-test-project
./scripts/robot-sim.sh create my-test-project robot-sim
```
then checking that cr-syncer and metadata-server logs both looked OK.
=> Enable metadata-server on GKE

src/go/cmd/cr-syncer/BUILD.bazel, src/go/cmd/cr-syncer/main.go, src/go/pkg/robotauth/robotauth.go, src/go/pkg/robotauth/robotauth_test.go
These are more limited than the GCP access token, as they can't list all
syncable CRs in the GKE cluster.
Tested by deploying the WIP cr-syncer-auth-webhook from the
rodrigoq/cr-syncer-auth branch, creating a fake-robot-sim CR, and then testing
the following cr-syncer flag combinations:
- `--robot-name=robot-sim      --use-robot-jwt=false`: syncs changes to the robot-sim CR
- `--robot-name=fake-robot-sim --use-robot-jwt=false`: syncs changes to the fake-robot-sim CR
- `--robot-name=robot-sim      --use-robot-jwt=true`: syncs changes to the robot-sim CR
- `--robot-name=fake-robot-sim --use-robot-jwt=true`: fails with Forbidden errors
=> cr-syncer: authenticate with robot JWTs from metadata-server

src/go/tests/relay/BUILD.bazel
https://github.com/googlecloudrobotics/core/issues/507 - it's 1-3%
flaky. I haven't looked into the details. Setting this flag makes Bazel
rerun the test so it's less likely to confuse people making unrelated
changes or affect presubmits.
=> Mark relay test as flaky

src/app_charts/base/BUILD.bazel, src/app_charts/base/cloud/cr-syncer-auth-webhook.yaml, src/app_charts/base/cloud/cr-syncer-policy.yaml, src/app_charts/base/cloud/kubernetes-api.yaml, src/go/cmd/cr-syncer-auth-webhook/BUILD.bazel, src/go/cmd/cr-syncer-auth-webhook/main.go
This just allows all requests so that they pass through to GKE with
their existing (GCP access token) credentials.
A followup will fix the TODO by accepting robot JWTs.
=> Add no-op cr-syncer-auth-webhook

src/go/cmd/cr-syncer-auth-webhook/BUILD.bazel, src/go/cmd/cr-syncer-auth-webhook/main.go, src/go/cmd/cr-syncer-auth-webhook/request.go, src/go/cmd/cr-syncer-auth-webhook/request_test.go
This adds code to verify and decode the JWTs and then to only allow
requests for resources corresponding to this robot.
Because this doesn't talk to the GKE apiserver itself, it is very
limited:
- it hardcodes the list of supported CRs
- it assumes that any CR with the suffix "robotName" is visible to that
robot (could be exploited by creating robots called 0, 1, 2, ...)
I've tested this by setting --use-robot-jwt=true on the cr-syncer on a
test system, but the new codepath won't be used until that becomes the
default.
=> Implement cr-syncer-auth-webhook

src/go/cmd/cr-syncer/health.go
For simplicity, the health check doesn't limit its request to a single
resource. This generates a "robot impersonation rejected" log message in
the cloud when it tries to list all Robot CRs. This doesn't break the
check, since it only fails on 401 but this gets a 403. However, the log
message is confusing.
Instead, we can check for robottypes, which allows a successful &
simpler request.
Tested by pushing the cr-syncer change to the GKE cluster created by
scripts/robot-sim.sh (with --use-robot-jwt=true) and verifying that the
error logs from the cr-syncer-auth-webhook stop.
=> cr-syncer: list robottypes in Health check

src/go/cmd/token-vendor/README.md, src/go/cmd/token-vendor/api/v1/v1.go, src/go/cmd/token-vendor/app/tokenvendor.go, src/go/cmd/token-vendor/app/tokenvendor_test.go
This will allow metadata-server or other clients (k8s-auth-plugins) to select which of the allowed service-accounts to use.
=> Proposal for token-vendor api-extension.

MODULE.bazel.lock, deploy.sh, non_module_deps.bzl, src/bootstrap/cloud/terraform/input.tf, src/bootstrap/cloud/terraform/versions.tf
We need to strip the quotes from the ingress-ip output. This otherwise breaks
our charts left and right.
Lets again roll this out everywhere, so that we can finally make the jump
to 1.x next.
=> Upgrade terraform to 0.15.5.

deploy.sh, src/bootstrap/cloud/terraform/registry.tf
GAR does not create any default repos. Hence import the existing ones.
Without this change creating new projects fails as we try to setup IAM memberships for repos that don't exist.
=> Import and create default artifact repositories.

src/go/cmd/token-vendor/api/v1/BUILD.bazel, src/go/cmd/token-vendor/api/v1/v1.go, src/go/cmd/token-vendor/api/v1/v1_test.go, src/go/cmd/token-vendor/repository/k8s/BUILD.bazel, src/go/cmd/token-vendor/repository/k8s/k8s.go, src/go/cmd/token-vendor/repository/k8s/k8s_test.go, src/go/cmd/token-vendor/repository/memory/memory.go, src/go/cmd/token-vendor/repository/memory/memory_test.go, src/go/cmd/token-vendor/repository/repository.go
Previously we returned "" and later changed that to a nil struct. This causes panics, as we also don't return any error and without it dereference the returned value.
Define an error, return it and update the commetns accordingly.
=> Refactor the repository to return NotFound for unknown keys

src/app_charts/token-vendor/cloud/token-vendor.yaml
This aligns the default logging with the other services.
=> Set def. log level for token-vendor to WARN

src/app_charts/base/cloud/cert-ingress.yaml, src/app_charts/base/cloud/kubernetes-api.yaml, src/app_charts/base/cloud/oauth2-proxy.yaml, src/app_charts/k8s-relay/cloud/ingress.yaml, src/app_charts/prometheus/cloud/grafana-ingress.yaml, src/app_charts/prometheus/cloud/prometheus-ingress.yaml, src/app_charts/prometheus/cloud/prometheus-relay.yaml, src/app_charts/token-vendor/cloud/ingress.yaml
This ensures that one ingress owns the tls-cert and avoids some repetition of the 'tls' block. The cert is determined through the 'host' field in the rules.
=> Add a placeholder ingress for the cert.

MODULE.bazel, src/app_charts/base/BUILD.bazel, src/go/cmd/token-vendor/api/v1/BUILD.bazel, src/go/cmd/token-vendor/repository/k8s/BUILD.bazel, src/go/tests/BUILD.bazel, src/go/tests/relay/BUILD.bazel, src/proto/http-relay/BUILD.bazel, third_party/kubernetes_proto/meta/BUILD.bazel, third_party/kubernetes_proto/runtime/BUILD.bazel, third_party/kubernetes_proto/schema/BUILD.bazel
Run `buildifier --lint=fix  -r -v .`. This adds loads for the rules that were removed from Bazel 8. By Bazel 9 automatic loads will be disabled and all loads will need to be explicitly present.
Remove @rules_proto dependency from MODULE.bazel. This has been replaced with @protobuf.
Add @rules_shell dependency to MODULE.bazel. This is needed for the used Shell rules.
See: https://github.com/bazelbuild/bazel/issues/25755
=> Run buildifier to add loads

src/app_charts/base/cloud/nginx-ingress-controller.yaml
We only need this in a handful of cases, but because we define the log format here there is no easy way to change it for specific projects.
=> Log x-forwarded-for

src/app_charts/token-vendor/cloud/ingress.yaml, src/go/cmd/token-vendor/README.md, src/go/cmd/token-vendor/api/v1/v1.go, src/go/cmd/token-vendor/api/v1/v1_test.go, src/go/cmd/token-vendor/app/BUILD.bazel, src/go/cmd/token-vendor/app/tokenvendor.go, src/go/cmd/token-vendor/app/tokenvendor_test.go, src/go/cmd/token-vendor/repository/k8s/k8s.go, src/go/cmd/token-vendor/repository/k8s/k8s_test.go, src/go/cmd/token-vendor/repository/memory/memory.go, src/go/cmd/token-vendor/repository/memory/memory_test.go, src/go/cmd/token-vendor/repository/repository.go
This endpoint allows to configure optional settings for a specific key, such as additional serviceacount that can be impersonated.
=> Add new "public-key.configure" endpoint for token-vendor

src/app_charts/base/cloud/cr-syncer-auth-webhook.yaml, src/app_charts/base/cloud/cr-syncer-policy.yaml, src/app_charts/base/cloud/kubernetes-api.yaml, src/app_charts/base/values-cloud.yaml
We previously mistakenly assumed .Values.onprem_federation was a
boolean, but it seems that deploy.sh passes all values through as
strings. I don't remember if there is a good reason for this...
To align with other switches like .Values.app_management, let's
stringly-type this too.
Tested by setting ONPREM_FEDERATION=true/false in config.sh, deploying,
and checking for the deployment in GKE.
=> Allow switching off the cr-syncer-auth-webhook

src/app_charts/base/robot/gcr-credential-refresher.yaml, src/app_charts/base/robot/metadata-server.yaml, src/app_charts/base/values-robot.yaml, src/go/cmd/gcr-credential-refresher/main.go, src/go/cmd/metadata-server/main.go, src/go/cmd/metadata-server/metadata.go, src/go/pkg/robotauth/robotauth.go
Allows setting default service account used by metadata server and gcr-credentials-refresher in order to enable token vendor to consider alternatives for creating new tokens overriding default behavior for annotated device registration.
=> Allow setting default service account for robot

src/app_charts/k8s-relay/cloud/service-monitor.yaml, src/app_charts/prometheus/cloud/prometheus-relay.yaml
When using a lot of clients on a relay, these configs can be used to e.g. group the metrics.
See b/431135959#comment6
=> Allow to configure metricsRelabelings

src/go/cmd/cr-syncer-auth-webhook/BUILD.bazel, src/go/cmd/token-vendor/repository/memory/BUILD.bazel
bazel run :gazelle
This make it easier to run cleaning for other PRs, and ensures
request_test runs in CI for example.
=> Run gazelle

src/app_charts/prometheus/prometheus-robot.values.yaml
This reduces the metric cardinality 3x (from 4.5k to <1.5k on one system
I tried), keeps the same scrape duration (~70ms), and adds some helpful
metrics for CPU models and network device drivers.
=> Tune node exporter

src/bootstrap/cloud/terraform/cluster.tf
This only sets the channel to be used when applying the next update given the configured maintenance window.
Tested manually.
=> Set the release-channel for GKE clusters to STABLE for consistency
