googlecloudrobotics/core

- src/bootstrap/cloud/terraform/service-account.tf
> Remove legacy bindings for GCE default SA

- src/app_charts/base/fluent-bit-helm.sh
- src/app_charts/base/fluent-bit-values.yaml
- src/app_charts/base/robot/fluent-bit.yaml
> fluent-bit: add tolerations and update to 2.0.9

- src/go/cmd/metadata-server/main.go
- src/go/cmd/metadata-server/metadata.go
This s a preparation to a policy on ADC usage.
> Print more details on peers relying on ADCs.

- src/app_charts/token-vendor/cloud/token-vendor.yaml
Fix for my yaml cleanup from yesterday.
> Drop training comma in yaml

- src/app_charts/base/robot/metadata-server.yaml
- src/go/cmd/metadata-server/main.go
I don't see any reason for using an env-var for that extra param. Hence simplify the code a bit. Also do some better check on the given ip address.
> Use flags instead of flags and env-vars.

- .github/ci/integration_test.sh
This file was renamed in https://github.com/googlecloudrobotics/core/pull/138 but I forgot to update this reference.
> Fix missing rename

- src/go/pkg/gcr/update_gcr_credentials.go
Investigating b/281647304, I've observed some gcr-credential-refresher instances that hang forever, logging nothing. The stacktrace points to this retry loop, so adding a limit should prevent the hang from breaking the gcr-credential-refresher, plus give us more info on the root cause.
> Avoid silent hang when failing to patch SA

- src/bootstrap/cloud/terraform/service-account.tf
Use compact form to represent the roles. Drop unused roles.
> Update robot-service roles.

- .github/workflows/check-bazel.yml
This aims to help debug issues like:
```
Starting local Bazel server and connecting to it...
Error: Process completed with exit code 37.
```
> Dump bazel logs after build

- src/app_charts/base/fluent-bit-values.yaml
- src/app_charts/base/robot/fluent-bit.yaml
this uses the systemd plugin to get around access problems of the kmsg plugin
> fluent-bit: add kernel log

- src/app_charts/base/relay-dashboard.json
The relay has now metrics for backend and overhead.
> Add panels for the 2 new histograms.

- src/go/tests/relay-bench.sh
The shell script setup a local relay and drives some tests.
> Add a benchmark setup for the relay.

- docs/how-to/setting-up-oauth.md
This is needed for new consent screens.
> Add User Type

- src/go/tests/relay_test.sh
This requires some hacks to make gcloud happy in the test environment. I confirmed that it fails with `TEST FAILED: id command did not run, output was ""`.
b/293827843
> Use gke-gcloud-auth-plugin in relay test

- deploy.sh
This fixes first-time deploys.
> Move VPA setup to after terraform runs

- src/go/pkg/controller/chartassignment/release.go
The chart-assignment-controller expands and applies Helm charts in background goroutines by calling from controller.go into release.go. Then, it periodically checks the status ("phase") in a struct shared with the background goroutine and updates the ChartAssignment status.
When updating an existing chart, there is a race between the background goroutine (running `release.update()`), which changes the phase from Ready to LoadingChart, and the controller goroutine (calling `release.setStatus()` from `Reconciler.reconcile()`), which queries the phase and updates the status. I suspect that this race was introduced by a change that ironically described itself as "overall simplifying the controller", although the only repro I have so far is that it happens in <1% of our cloud integration …
> Fix a chart-assignment-controller race

- src/bootstrap/cloud/terraform/cluster.tf
> Bump min k8s version for additional region.

- .github/ci/Dockerfile.integration-test-image
- .github/ci/integration_test_cloudbuild.yaml
- .github/workflows/check-bazel.yml
- .github/workflows/release.yml
Also minor improvements to the integration test image. The size is reduced from 4.17G to 4.05G.
> Update Bazel to 6.3.2

- src/go/cmd/http-relay-client/client/client.go
- src/go/tests/relay/BUILD.bazel
- src/go/tests/relay/in_process_relay_test.go
This is the first in-process relay test.
> In-process relay tests

- .github/ci/deploy_navtest.sh
- .github/ci/presubmit.sh
- .github/ci/release_binary.sh
- .github/workflows/check-bazel.yml
- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
This should provide more debugging information on error.
This requires an update to 22.04 to get a newer curl. This might break after merging if  I didn't do the update in the right places.
> Use --fail-with-body

- deploy.sh
This is a step towards removing the blanket objectAdmin ACL.
(b/299475780) It's a second attempt after the rollback in #237.
As far as I can tell, robot-service@ does not need to read other files
from CRC buckets (config.sh, crc_version.txt, etc) in the general case,
although integration tests might need more privilege.
> Allow robot-service@ to read from GCR explicitly.

- WORKSPACE
* add sample commands
* add a note on the used version for the ptables image
> Update comments for updating the images.

- METADATA
- current_versions.txt
- new_versions.txt
- src/app_charts/base/cloud/oauth2-proxy.yaml
I've checked the releases and there are no breaking changes. https://github.com/oauth2-proxy/oauth2-proxy/releases
> Update oauth2-proxy to 7.5.1

- src/go/cmd/http-relay-client/client/client.go
This should fix issues we encountered when (re)configuring the network
on the nodes. b/313612734
> http-relay-client: Use HTTP/2 PING to recover from network issues

- src/app_charts/base/cloud/cert-manager-issuers.yaml
> Make letsencrypt-prod a ClusterIssuer

- src/go/pkg/synk/synk.go
This follows the precedent set in client-go's [memcache](https://github.com/kubernetes/client-go/commit/0bc91705fa50a531b8a1ee9dca3ef063ca71bb0c).
The discovery client's `ServerGroupsAndResources()` call sometimes throws up empty response errors if a metrics server (namely GCP's custom metric server) neglects to populate its resource list. This is not considered an error.
The [bump of client-go's version](https://github.com/googlecloudrobotics/core/pull/264) fixed `memcache.go`, but we also need to account for it in our code.
Tested with a test deploy, the CAC works as expected.
---
**Note**: Logging the downgraded error generates quite a few spurious logs on startup (in fact, I think it generates one log PER chart update call, so each time a chart is updated, we'll get a printout...) …
> Downgrade "empty response" error in discovery client to info log for metrics

- src/go/pkg/controller/chartassignment/release.go
This will more consistently log when a chart fails.
> Log the error when we don't retry again.

- src/go/cmd/http-relay-client/main.go
https://github.com/googlecloudrobotics/core/pull/260 had no effect
because the default config settings require additional support in
main.go to make it through the client.
This eliminates the mistake and reduces the number of lines needed per
config setting, especially for those that don't (yet?) need a flag like
BackendResponseTimeout or ReadIdleTimeout.
This should actually fix issues we encountered when (re)configuring the network
on the nodes. b/313612734
All credit to Koon Peng for figuring out my mistake here!
b/316473267#comment15. We should think about banning changes that are
authored and reviewed only by managers as we obviously don't have the
attention span to catch issues like this.
> Correctly apply relay config

- src/go/cmd/app-rollout-controller/main.go
- src/go/cmd/chart-assignment-controller/main.go
passing nil into ilog.Err will segfault.
> fix handling of nil return value of Manager.Start

- src/go/cmd/app-rollout-controller/BUILD.bazel
- src/go/cmd/app-rollout-controller/main.go
- src/go/cmd/chart-assignment-controller/BUILD.bazel
- src/go/cmd/chart-assignment-controller/main.go
* add a flag for the probe port
* replace the handler by the identical healthz.Ping
* handle err for adding the handler
> Small code cleanup wrt health probes.

- src/go/pkg/synk/synk.go
When we upgrade clusters to 1.28 we also get:
```
discover server resources:
unable to retrieve the complete list of server APIs:
metrics.k8s.io/v1beta1:
stale GroupVersion discovery:
metrics.k8s.io/v1beta1
```
> Implement the workaround as others do.

- src/app_charts/base/cloud/cert-manager-certificates.yaml
Fixes on 1ba3da9fd14d2388ad2f8b30358324c2c8629ea9.
> Also update the issuer type for the prod cert.

- src/go/pkg/synk/synk.go
Reverts googlecloudrobotics/core#307
> Revert "Implement the workaround as others do."

- WORKSPACE
> Switch bazel toolchain repo.

- WORKSPACE
I've forgot to change the download url and the doc url in the comment.
See #331, #336
> Update remaining urls for new toolchain rules.

- src/app_charts/prometheus/prometheus-robot.values.yaml
Also update the comments. I hope this will further reduce the risk of running out of disk space.
> Create headroom between retentionSize and sizeLimit

- .github/ci/.bazelrc
This aims to mitigate http://b/346715839.
> Increase retries for BES.

- docs/overview.md
Found another one !
https://en.wiktionary.org/wiki/accross
> Fix another typo in overview.md

- docs/concepts/config.md
- docs/concepts/device_identity.md
- docs/developers/debug-auth.md
Since I am reading the entire doc to understand the architecture, I'll try to improve it along the way...
> [WIP] Fix multiple typos in documentation

- src/bootstrap/cloud/terraform/dns.tf
I realized that this was non-obvious when discussing with Rastislav.
> Add explanatory comments

- src/bootstrap/cloud/terraform/cluster.tf
- src/bootstrap/cloud/terraform/registry.tf
- src/bootstrap/cloud/terraform/service-account.tf
This fixes setup-robot.sh invocations.
> Also update human-acl gar access.

- deploy.sh
No-op, but ensures that we don't define x and use y instead.
> Use the same variable that we have in the config.

- deploy.sh
It actually can be done in terraform now, but we're not actively using it.
> Drop VPA setup.

- deploy.sh
- scripts/common.sh
This will provide some update history. Sample log entry: https://cloudlogging.app.goo.gl/nt3CVKVVJRHShbz18
```json
{
"insertId": "jg0wiyg1b69tkq",
"jsonPayload": {
"message": "./deploy.sh update",
"git-ref": "efa2c86",
"hostname": "dev.example.com",
"git-branch": "ensonic/log",
"user": "ensonic",
},
"resource": {
"type": "global",
"labels": {
"project_id": "robco-ensonic"
}
},
"timestamp": "2024-07-30T08:30:15.694430982Z",
"severity": "INFO",
"logName": "projects/robco-ensonic/logs/cloud-robotics-deploy",
"receiveTimestamp": "2024-07-30T08:30:15.694430982Z"
}
```
> Add a cloud log trace to deploy-invocations.

- deploy.sh
Let's simply use echo as it is a single line.
> Cleanup bad indentation of the "additional regions section".

- src/go/cmd/metadata-server/metadata.go
The previous approach got the metadata server stuck and prevented the setup of the iptables rule With this change, the metadata server can setup and only reject requests it cannot service due to the missing information
Using atomic operations since the project 0 should never show up and it is
* easier than proper locking
* does not lead to congestion on the read path we cannot wait for the resolution, but assume downstream clients retry
> Allow to start metadata-server without internet connection

- scripts/BUILD.bazel
- src/bootstrap/cloud/BUILD.bazel
See e.g.:
https://github.com/googlecloudrobotics/core/actions/runs/10877833828/job/30179812016#step:6:105
> Include new script to fix the release.

- .github/ci/common.sh
- deploy.sh
Use a variable in the script to make this a bit more obvious. Also fix external module references.
> Handle runfiles changes from bazel update.

- deploy.sh
Breakage is before reelase runs.
> More debugging in deploy.sh

- deploy.sh
- src/app_charts/base/app_management_test.sh
This will hopefully ensure that things don#t fall apart with next version:
https://github.com/googlecloudrobotics/core/issues/417#issuecomment-2363343809
> workaround bazel runfiles changes

- deploy.sh
- src/app_charts/base/app_management_test.sh
Reverts googlecloudrobotics/core#445
Fails in teh CI: https://github.com/googlecloudrobotics/core/actions/runs/10959202675/job/30431049560#step:4:178
> Revert "workaround bazel runfiles changes"

- deploy.sh
- src/app_charts/base/app_management_test.sh
- src/bootstrap/cloud/terraform/README.md
- src/go/pkg/kubetest/kubetest.go
See #447. Tested with:
```
bazel test //src/app_charts/base:app_management_test
USE_BAZEL_VERSION=b084956e23a6e50e35fe8886d0f3f7e05f718155 bazel test //src/app_charts/base:app_management_test
```
> Fix app_management_test at HEAD

- deploy.sh
This was reenabling the contaienrregistry api in tests.
> Switch to artifact registry.

- MODULE.bazel.lock
We've udpated bazel and some entries changed.
> Add updated lockfile.

- MODULE.bazel
- MODULE.bazel.lock
For changes see: https://github.com/bazel-contrib/rules_oci/releases/tag/v2.0.1
See #451
> Bump rules_oci to address bazel-head compatibility.

- src/go/cmd/token-vendor/README.md
> API proposal for the custom sa associations.

- deploy.sh
We only experimented with that in robco-ensonic. No need to run this for all projects,
> Remove some cleanup code.

- src/bootstrap/cloud/terraform/cluster.tf
- src/bootstrap/cloud/terraform/dns.tf
- src/bootstrap/cloud/terraform/registry.tf
- src/bootstrap/cloud/terraform/service-account.tf
- src/bootstrap/cloud/terraform/workload-identity.tf
See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#attributes-reference
> Use the member field for better readbility.

- src/app_charts/base/fluent-bit-helm.sh
- src/app_charts/base/robot/fluent-bit.yaml
> Update fluentbit to latest release

- src/app_charts/base/fluent-bit-values.yaml
- src/app_charts/base/robot/fluent-bit.yaml
> Remove the node-exporter config from fluentbit

- src/go/cmd/app-rollout-controller/main.go
- src/go/cmd/chart-assignment-controller/main.go
- src/go/cmd/cr-syncer/main.go
- src/go/cmd/metadata-server/main.go
- src/go/cmd/token-vendor/main.go
Also mark existing "verbose" flag as deprecated.
See b/393312849
> Add a log_level flag to all services.

- src/bootstrap/cloud/terraform/registry.tf
Right now we have to rerun as the repos and usually not immediately ready.
> Add a depends_on to fix first-time installs.

- src/bootstrap/cloud/terraform/cluster.tf
Configure the weekend for maintenance operations.
> Add a maintenance schedule for the cluster.

- src/bootstrap/cloud/terraform/registry.tf
Reverts googlecloudrobotics/core#518
Removes images used in production.
chat: https://chat.google.com/room/AAAAjJIMTAM/pcWocoBr90E/pcWocoBr90E?cls=10
> Revert "Add cleanup policy for artifact repositories."

- src/go/cmd/token-vendor/api/v1/v1.go
We recently refined the api to return not found.
> Update v1.go api comments

- src/app_charts/token-vendor/cloud/dashboard.yaml
> Rename configmap to have a unique name

- src/app_charts/base/cloud/nginx-ingress-controller.yaml
Reverts googlecloudrobotics/core#570 - dependency has now been fixed.
> Revert "Revert "Re-enable connection reuse""
